name: Maven Verify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/maven-verify_.yaml
    secrets: inherit
    with:
      java-version: '17'
