name: Reusable Maven Verify

on:
  workflow_call:
    inputs:
      java-version:
        description: 'JDK version to build with'
        type: string
        required: true
      revision:
        description: 'Revision'
        type: string
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_GPG_KEY: ${{ secrets.maven_gpg_key }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven_gpg_passphrase }}
    steps:

      - uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            11
            8
            ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: 'Verify Java environment variables'
        shell: bash
        # language="shell script"
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "JAVA_HOME_8_X64: $JAVA_HOME_8_X64"
          echo "JAVA_HOME_11_X64: $JAVA_HOME_11_X64"
          echo "JAVA_HOME_17_X64: $JAVA_HOME_17_X64"

      - name: 'Configure Git User'
        shell: bash
        # language="shell script"
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Invoke Maven Tests
        shell: bash
        env:
          REVISION: ${{ inputs.revision }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        # language="shell script"
        run: |
          declare -a mvnArgs_=( -B -ntp -e )
          if [ -n "${REVISION}" ] ; then mvnArgs_+=( "-Drevision=${REVISION}" ) ; fi
          mvn "${mvnArgs_[@]}" clean verify -Prun-its
