name: Maven Deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      deploy-server:
        description: 'Distribution server-id'
        type: choice
        default: central
        options:
          - central
          - emergent-nexus

jobs:
  invoke-deploy:
    #if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
    permissions:
      contents: write
    uses: emergentdotorg/github-actions/.github/workflows/maven-deploy.yaml@v3
    secrets: inherit
    with:
      java-version: 17
      deploy-server: ${{ inputs.deploy-server }}
      release-branches: 'main,master,release.*'

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-deploy
    steps:
      # language="shell script"
      - run: echo version=${{ needs.invoke-deploy.outputs.version }}
